### ISSUE TITLE
running prestart hook 0 caused "signal: segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by pschiffe** [projectatomic/oci-systemd-hook#32] opened 2016-11-29 14:05 UTC
When trying to use oci-systemd-hook with runc container, I get:
```
Nov 29 12:55:48 gce-agents runc[23785]: process_linux.go:329: running prestart hook 0 caused "signal: segmentation fault (core dumped): "
Nov 29 12:55:48 gce-agents runc[23830]: open /run/runc/ga/state.json: no such file or directory
```

I've compiled oci-systemd-hook from master branch of this repo. And I'm using this config file: [config.json.template.txt](https://github.com/projectatomic/oci-systemd-hook/files/619091/config.json.template.txt)

**Comment by rhatdan** [comment] 2016-11-29 14:14
The code we generate hooks with look like the following, So I think we need to add these.

configPath is a path to the json file used for the container.  We probably need to figure out how to handle this.  Basically it is looking for the CMD field, to see if it is "init"

+                       specHooks.Prestart = append(specHooks.Prestart, specs.Hook{
+                               Path: hook,
+                               Args: []string{hook, "prestart", configPath},
+                               Env:  []string{"container=docker"},
+                       },
+                       )
+                       specHooks.Poststop = append(specHooks.Poststop, specs.Hook{
+                               Path: hook,
+                               Args: []string{hook, "poststop", configPath},
+                               Env:  []string{"container=docker"},
+                       },

**Comment by giuseppe** [comment] 2016-11-29 17:35
what error do you get in the journal?

One issue can be that `/etc/machine-id` is not writeable, we may teach oci-systemd-hook to not try to write it if it already has a value.

**Comment by giuseppe** [comment] 2016-11-29 17:39
you can try in order:

1) quickest check make readonly=false, if it still crashes then the issue is somewhere else
2) create an empty temporary file and add a rw bind mount to it:

```
		{
			"source": "/tmp/foo",
			"destination": "/etc/machine-id",
			"type": "bind",
			"options": [
				"rw"
			]
		},
```

**Comment by pschiffe** [comment] 2016-11-30 14:43
In the journal only interesting thing is:
```
Nov 29 12:55:48 gce-agents runc[23785]: process_linux.go:329: running prestart hook 0 caused "signal: segmentation fault (core dumped): "
Nov 29 12:55:48 gce-agents runc[23830]: open /run/runc/ga/state.json: no such file or directory
```

With `readonly=false` I'm not able to install system container:
```
$ sudo atomic install --system ga
Extracting to /var/lib/containers/atomic/ga.0
Invalid configuration file.  Only readonly images are supported
```

And the empty temporary file also doesn't work:
```
Nov 30 14:39:34 gce-agents runc[30043]: rootfs_linux.go:53: mounting "/var/lib/containers/atomic/ga.0/rootfs/etc/machine-id" to rootfs "/var/lib/containers/atomic/ga.0/rootfs" caused "no such device"
Nov 30 14:39:34 gce-agents runc[30081]: open /run/runc/ga/state.json: no such file or directory
```

I tried your example and also `/opt/foo` (`/opt` is not on tmpfs), but result was the same.
```
        {
            "source": "/opt/foo",
            "destination": "/etc/machine-id",
            "type": "bind",
            "options": [
                "rw"
            ]
        }
```

**Comment by rhatdan** [comment] 2016-11-30 14:45
Does /etc/machine-id exists on the image.

Easy to check by using atomic mount

atomic mount IMAGE /mnt
ls -l /mnt/etc/machine-id

If machine-id does not exist. then the code will attempt to create the mount point.  

Bottom line oci-systemd-hook needs to be able to handle a read-only container.

**Comment by pschiffe** [comment] 2016-11-30 16:47
Well, I'm confused right now. I removed the `/etc/machine-id` from image in Dockerfile:
```
FROM centos:7
MAINTAINER "Peter Schiffer" <pschiffe@redhat.com>
COPY google-cloud.repo /etc/yum.repos.d/google-cloud.repo
RUN yum -y --setopt=tsflags=nodocs install \
        ethtool \
        google-compute-engine \
        google-compute-engine-init \
        google-config \
    && yum clean all
STOPSIGNAL SIGRTMIN+3
ENV container=docker
RUN rm -f /etc/machine-id
COPY manifest.json service.template config.json.template /exports/
CMD [ "/usr/sbin/init" ]
```

When I check if the `/etc/machine-id` exists with:
```
$ sudo docker run -it --rm ga bash
[root@3b01c226b233 /]# ll /etc/mach*
ls: cannot access /etc/mach*: No such file or directory
```

But with `atomic mount`:
```
[fedora@gce-agents gce-agents]$ ll /mnt/
total 0
[fedora@gce-agents gce-agents]$ sudo atomic mount ga /mnt 
[fedora@gce-agents gce-agents]$ ll /mnt/etc/machine-id 
-rwxr-xr-x. 1 root root 0 Nov 30 15:47 /mnt/etc/machine-id
```

I don't get it.

```
$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ga                  latest              8fc0fb471739        26 minutes ago      223.4 MB
docker.io/centos    7                   0584b3d2cf6d        3 weeks ago         196.5 MB
```

```
$ sudo atomic images list
   REPOSITORY         TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
   ga                 latest   8fc0fb471739   2016-11-30 16:14   223.41 MB      Docker    
   docker.io/centos   7        0584b3d2cf6d   2016-11-02 19:52   196.51 MB      Docker    
   ga                 latest   fe3dce479da6   2016-11-30 16:32                  system
```

I'm using `sudo atomic pull --storage ostree docker:ga` to put `ga` image to ostree. When I run:
```
$ sudo atomic install --system ga
$ sudo systemctl restart ga
```

I get:
```
Nov 30 16:43:21 gce-agents runc[3655]: rootfs_linux.go:53: mounting "/var/lib/containers/atomic/ga.0/rootfs/etc/machine-id" to rootfs "/var/lib/containers/atomic/ga.0/rootfs" caused "no such
Nov 30 16:43:21 gce-agents runc[3695]: open /run/runc/ga/state.json: no such file or directory
```

I removed all docker and system images and rebuilt the `ga` from scratch, but it's still the same.

**Comment by giuseppe** [comment] 2016-11-30 17:12
is your code somewhere?  I can try to build the image and give it a try

**Comment by pschiffe** [comment] 2016-11-30 17:15
Sorry, no github yet, but here you go: [gce.zip](https://github.com/projectatomic/oci-systemd-hook/files/622484/gce.zip)

**Comment by giuseppe** [comment] 2016-12-01 12:25
I could not reproduce the segfault here, I am using the latest upstream version.

I have done some changes to your container, it seems to work for me like this.  As far I know this is the first working system container using systemd :)

Few notes:
1) I have moved capabilities under "process" in the config.json, added a few ones needed by systemd
2) rm -rf /var/lib/rpm/__db.* to avoid errors from systemd-tmpfiles on boot on a ro path.
3) dropped ExecStop in favor of KillSignal, so that the systemd process is correctly terminated.

```
FROM centos:7
MAINTAINER "Peter Schiffer" <pschiffe@redhat.com>

COPY google-cloud.repo /etc/yum.repos.d/google-cloud.repo

RUN yum -y --setopt=tsflags=nodocs install \
        ethtool \
        google-compute-engine \
        google-compute-engine-init \
        google-config \
    && yum clean all

STOPSIGNAL SIGRTMIN+3

ENV container=docker

RUN rm -f /etc/machine-id /etc/fstab /var/lib/rpm/__db.*

COPY manifest.json service.template config.json.template /exports/

CMD [ "/usr/sbin/init" ]
```

```
[Unit]
Description=Linux Guest Environment for Google Compute Engine

[Service]
ExecStart=$EXEC_START
KillSignal=SIGRTMIN+3

Restart=on-failure
WorkingDirectory=$DESTDIR

[Install]
WantedBy=multi-user.target
```


```
{
    "ociVersion": "1.0.0",
    "platform": {
        "os": "linux",
        "arch": "amd64"
    },
    "process": {
        "terminal": false,
        "user": {
            "uid": 0,
            "gid": 0
        },
        "args": [
            "/sbin/init"
        ],
        "env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "TERM=xterm",
            "container=docker"
        ],
        "cwd": "/",
        "capabilities": [
            "CAP_SYS_ADMIN",
            "CAP_CHOWN",
            "CAP_SETUID",
            "CAP_SETGID",
            "CAP_FOWNER",
            "CAP_DAC_OVERRIDE",
            "CAP_FSETID",
            "CAP_SETFCAP",
            "CAP_KILL",
            "CAP_SETPCAP",
            "CAP_NET_BIND_SERVICE",
            "CAP_NET_RAW",
            "CAP_NET_BROADCAST",
            "CAP_AUDIT_WRITE"
        ]
    },
    "root": {
        "path": "rootfs",
        "readonly": true
    },
    "mounts": [
        {
            "destination": "/proc",
            "type": "proc",
            "source": "proc",
            "options": [
		"ro"
	    ]
        },
        {
            "destination": "/dev",
            "type": "tmpfs",
            "source": "tmpfs"
        },
        {
            "destination": "/dev/pts",
            "type": "devpts",
            "source": "devpts"
        },
        {
            "destination": "/dev/shm",
            "type": "tmpfs",
            "source": "shm"
        },
        {
            "destination": "/dev/mqueue",
            "type": "mqueue",
            "source": "mqueue"
        },
        {
            "destination": "/sys",
            "type": "sysfs",
            "source": "sysfs",
            "options": [
                "ro"
            ]
        },
        {
            "destination": "/var/log",
            "type": "tmpfs",
            "source": "tmpfs"
        }
    ],
    "hostname": "gce",
    "hooks": {
        "prestart": [
            {
                "path": "/usr/libexec/oci/hooks.d/oci-systemd-hook"
            }
        ],
        "poststop": [
            {
                "path": "/usr/libexec/oci/hooks.d/oci-systemd-hook"
            }
        ]
    },
    "linux": {
        "rlimits": [
            {
                "type": "RLIMIT_NOFILE",
                "hard": 1024,
                "soft": 1024
            }
        ],
        "resources": {
            "devices": [
                {
                    "allow": false,
                    "access": "rwm"
                }
            ]
        },
        "namespaces": [
            {
                "type": "pid"
            },
            {
                "type": "ipc"
            },
            {
                "type": "uts"
            },
            {
                "type": "mount"
            }
        ]
    }
}
```

for simplicity, I have uploaded the tarball here (github didn't like my zip file):

http://scrivano.org/static/gce.tar

**Comment by pschiffe** [comment] 2016-12-01 16:49
@giuseppe thanks for great help. But unfortunately, I'm still seeing the segfault :-(
I'm running Fedora 24 in GCE cloud (F25 doesn't work) with couple of packages from rawhide:
```
$ rpm -q docker runc atomic
docker-1.12.3-25.git7b5044b.fc26.x86_64
runc-1.0.0-1.rc1.git04f275d.fc26.x86_64
atomic-1.14.0-1.dev.gite937650.fc26.x86_64
```
oci-systemd-hook is compiled from master branch. What did you mean by latest upstream version where you can't reproduce the segfault? Which package?

**Comment by giuseppe** [comment] 2016-12-01 17:16
Can you try:

```
cd /var/lib/containers/atomic/gce.0
runc run foo
```

Does it segfault?

What if you try (container must be anything != "docker")?

```
container=foo runc run foo
```

If the env variable fix your segfault then this patch is needed: https://github.com/projectatomic/oci-systemd-hook/pull/33

**Comment by pschiffe** [comment] 2016-12-02 09:09
@giuseppe yop, I needed that patch. Now I don't see any segfault, thanks!

**Comment by rhatdan** [comment] 2016-12-02 15:31
@giuseppe Merged altnerate patch https://github.com/projectatomic/oci-systemd-hook/pull/34

**Comment by rhatdan** [comment] 2016-12-02 15:33
@lsm5 we need a new oci-systemd-hook built for Fedora and RHEL7.

**Comment by rhatdan** [comment] 2017-07-13 19:55
THis has been long fixed.

**Closed by rhatdan** 2017-07-13 19:55 UTC
